name: expected-goals
channels:
  - anaconda
  - conda-forge
dependencies:
  - anaconda::jupyter
  - anaconda::pandas
  - anaconda::scipy
  - anaconda::seaborn
  - anaconda::beautifulsoup4
  - anaconda::pyarrow
  - anaconda::pillow
  - anaconda::openpyxl
  - anaconda::pillow
  - anaconda::shapely
  - anaconda::requests
  - anaconda::statsmodels
  - conda-forge::fuzzywuzzy
  - conda-forge::metaphone
  - pip
  - pip:
      - mplsoccer
      - lightgbm
      - adjustText
      - fuzzymatcher
      - scikit-optimize
      - imbalanced-learn
      - scikit-learn == 0.23.0
