name: expected-goals
channels:
  - conda-forge
dependencies:
  - altair
  - geopandas
  - jupyterlab
  - lightgbm
  - matplotlib
  - mplsoccer
  - openpyxl
  - pandas
  - pdpbox
  - pillow
  - pyarrow
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - shap
  - shapely
  - statsmodels
  - pip
  - pip:
      - adjustText
      - splink
